### ISSUE TITLE
Doesn't work with latest version of github.com/pkg/term

### ISSUE THREAD

**Issue by creekorful** [jaguilar/vt100#1]
Hello there!

Little issue to let you know that your package doesn't work anymore when using with latest version of github.com/pkg/term.

I have written a patch to fix that, and can create a PR (with go module refactoring) if you are willing to review + merge it.

Here is the patch: https://salsa.debian.org/go-team/packages/golang-github-jaguilar-vt100/-/raw/debian/sid/debian/patches/patch-demo.patch

Would you be interested?

**Comment by jaguilar** [comment]
I would review and merge this PR.

**Comment by creekorful** [comment]
Thanks :)

I've opened the PR.
